"""migrations1

Revision ID: 7538bcb1695e
Revises: 
Create Date: 2024-08-11 20:19:13.026106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7538bcb1695e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('confirm', sa.Boolean(), nullable=True),
    sa.Column('photo_id', sa.String(), nullable=True),
    sa.Column('years', sa.Text(), nullable=True),
    sa.Column('probeg', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('fuel', sa.Text(), nullable=True),
    sa.Column('payment', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('subject_photo', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('money', sa.Text(), nullable=True),
    sa.Column('numeration_files', sa.Text(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('superadmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.BIGINT(), nullable=True),
    sa.Column('amount_som', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_adding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('message_id', sa.BIGINT(), nullable=True),
    sa.Column('ad_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paid_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=True),
    sa.Column('num', sa.BIGINT(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.BIGINT(), nullable=True),
    sa.Column('message_id', sa.BIGINT(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reklama',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_id', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('superadmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('count_ads', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('reklama')
    op.drop_table('paid_message')
    op.drop_table('message_adding')
    op.drop_table('chats')
    op.drop_table('card')
    op.drop_table('admins')
    op.drop_table('adding')
    # ### end Alembic commands ###
